import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AMARZONE",
  description: "Generated by create next app",
};

import { NotificationProvider } from "@/src/context/NotificationContext";
import { NotificationToaster } from "@/src/components/ui/notification/NotificationToaster";
import ReduxProvider from "../lib/provider/ReduxProvider";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReduxProvider>
          <NotificationProvider>
            {children}
            <NotificationToaster />
          </NotificationProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
